# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
description: Chainlink Feeds Indexer

# Global contract definitions for multi-chain support
contracts:
  - name: ChainlinkProxy
    handler: src/EventHandlers.ts
    events:
      - event: AnswerUpdated(int256 indexed current, uint256 indexed roundId, uint256 updatedAt)
  - name: RedstoneProxy
    handler: src/EventHandlers.ts
    events:
      - event: ValueUpdate(uint256 value, bytes32 dataFeedId, uint256 updatedAt)

# Enable unordered multichain mode for parallel processing
unordered_multichain_mode: true

# Network-specific configurations
networks:
  - id: 1 # Ethereum Mainnet
    start_block: 23100000
    contracts:
      - name: ChainlinkProxy # Reference to global contract definition
        address:
          - 0x7d4E742018fb52E48b08BE73d041C18B21de6Fb5 # ETH/USD (Mainnet)
      - name: RedstoneProxy # Reference to global contract definition
        address:
          - 0xd72a6BA4a87DDB33e801b3f1c7750b2d0911fC6C # BTC/USD (Polygon)

  # - id: 137 # Polygon Mainnet
  #   start_block: 73000000
  #   contracts:
  #     - name: ChainlinkProxy # Reference to global contract definition
  #       address:
  #         - 0x014497a2AEF847C7021b17BFF70A68221D22AA63

rollback_on_reorg: false

field_selection:
  transaction_fields:
    - "gasUsed"
    - "effectiveGasPrice"
